SELECT a.PRODUCT_ID, max(a.PRODUCT_NAME) as PRODUCT_NAME, a.PRICE * sum(b.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT a
 JOIN FOOD_ORDER b ON a.PRODUCT_ID = b.PRODUCT_ID
 AND DATE_FORMAT(b.PRODUCE_DATE, '%Y%m') = 202205
GROUP BY a.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
