SELECT a.CAR_ID, a.CAR_TYPE, FLOOR(a.DAILY_FEE * 30 * (100 - c.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR a
LEFT OUTER JOIN (
    SELECT CAR_ID, MAX(END_DATE) AS END_DATE 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
) b ON a.CAR_ID = b.CAR_ID 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c ON c.CAR_TYPE = a.CAR_TYPE AND c.DURATION_TYPE like('%30%')
WHERE a.CAR_TYPE IN ('SUV', '세단')
AND b.END_DATE < '20221101' AND b.CAR_ID IS NOT NULL
AND FLOOR(a.DAILY_FEE * 30 * (100 - c.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, a.CAR_TYPE ASC, a.CAR_ID DESC